/*
 * Copyright (c) 2010, Department of Information Engineering, University of Padova.
 * All rights reserved.
 *
 * This file is part of Merab.
 *
 * Merab is free software: you can redistribute it and/or modify it under the terms
 * of the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * Merab is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Merab.  If not, see <http://www.gnu.org/licenses/>.
 *
 * ===================================================================================
 */

/**
 *
 * This is the application of the user interface. It shows the payload of the package
 * sent by a single node and save the data to a TXT file.
 * The payload contains this informations:
 * [ID]         	identification number of the sensor
 * [#Pkg]      		package number
 * [Temperature(°C)]	temperature
 * [Humidity(%RH)]   	humidity
 * [PAR (Lux)]		PAR
 * [TSR t(Lux)]		TSR
 *
 * See the help of this program calling java OutputSaver -h
 *
 * @date 25/05/2011 14:50
 * @author Filippo Zanella <filippo.zanella@dei.unipd.it>
 */

import java.io.*;
import java.lang.Math;
import net.tinyos.message.Message;
import net.tinyos.message.MessageListener;
import net.tinyos.message.MoteIF;
import net.tinyos.message.SerialPacket;
import net.tinyos.packet.BuildSource;
import net.tinyos.packet.PhoenixSource;
import net.tinyos.util.PrintStreamMessenger;

public class OutputSaver implements MessageListener
{

	private MoteIF mote;
	private DataSensorsMsg msg;
	public FileOutputStream outputFile;
	public PrintStream output;

	double temperature;
	double humidity;
	double humidity_true;
	double par;
	double tsr;
	//double voltage;

	static double V_REF = 1.5;

	public OutputSaver(MoteIF mif, String file, String source) {
		try
		{
			outputFile = new FileOutputStream(file + ".txt");
			output = new PrintStream(outputFile);
			output.println("##File generated by OutputSaver ##");
			output.println("");
			output.println("[ID]\t[#Pkg]\t[Temperature(°C)]\t[Humidity(%RH)]\t[Humidity[true](%RH)]\t[PAR(Lux)]\t[TSR(Lux)]");
			output.println("");
			System.err.println("Copyright (c) 2010, Department of Information Engineering, University of Padova.");
		    System.err.println("");
			System.out.print("Connecting to serial port...");
			mote = mif;

			mote.registerListener(new DataSensorsMsg(), this);
		}
		catch (IOException ioex) {
			System.err.println("Exception thrown when creating a file. Exiting.");
			System.err.println(ioex);
		}
		catch (Exception ex) {
			System.err.println("Couldn't contact serial port.");
			System.err.println(ex);
		}
		System.out.println("done.");
		System.out.println("Connected with " + source +  ".");
		System.out.println("OutputSaver started.");
		System.out.println("Saving data to file " + file + ".txt.");
	}

	synchronized public void messageReceived(int dest, Message m) {
		msg = (DataSensorsMsg) m;

		//voltage = (double)msg.get_voltage() / (double)4096 * (2 * V_REF);

		//temperature = -38.4 + 0.0098 * msg.get_temperature();		
		temperature = -39.6 + 0.01 * (double)msg.get_temperature();

		//humidity = -4  + 0.0405*(double)msg.get_humidity() - (double)0.0000028*msg.get_humidity()*msg.get_humidity();
		humidity = -2.0468 + 0.0367*(double)msg.get_humidity() - (double)1.5955e-6*msg.get_humidity()*msg.get_humidity();
		
		humidity_true = (temperature - 25) * (0.01 + 0.00008*msg.get_humidity()) + humidity;
		
		double I_par = ((double)msg.get_par() / 4096 * V_REF) / 100000; 
		par = 0.625 * 1e6 * I_par * 1000;

		double I_tsr = ((double)msg.get_tsr() / 4096 * V_REF) / 100000; 
		tsr = 0.769 * 1e5 * I_tsr * 1000;


		//System.out.println("Voltage: " + cutNumber(voltage,4) + " [V]");
		System.out.println("Temperature: " + cutNumber(temperature,6) + " [C]");
		System.out.println("Humidity: " + cutNumber(humidity,6) + " [%RH]");
		System.out.println("Humidity (real): " + cutNumber(humidity_true,6) + " [%RH]");
		System.out.println("PAR: " + cutNumber(par,6) + " [Lux]");
		System.out.println("TSR: " + cutNumber(tsr,6) + " [Lux]");
		try
		{
			output.println(msg.get_id() + "\t" + msg.get_counter() + "\t\t" + cutNumber(temperature,5)
				+ "\t\t" + cutNumber(humidity,5) + "\t\t" + cutNumber(humidity_true,5)
				+ "\t\t" + cutNumber(par,5) + "\t\t" + cutNumber(tsr,5));
		}
		catch (Exception e) {
			System.err.println("Exception thrown when writing the outputs. Exiting.");
			System.err.println(e);
		}
	}

	public String cutNumber(double str, int pos) {
		String s = str + "";
		if(pos>s.length())
			pos = s.length();
		return s.substring(0,pos);
	}

	private static void usage() {
		System.err.println("usage: OutputSaver [options] [-comm SOURCE] [-f FILE]");
		System.err.println("options:");
		System.err.println("-h\t\t Show this help");
		System.err.println("[-comm SOURCE]\t Set the serial source connection");
		System.err.println("[-f FILE]\t Save the data to a <FILE>.txt");
		System.err.println("");
		System.err.println("The default command is: OutputSaver -comm serial@/dev/ttyUSB0:tmote -f data");
	}

	public static void main(String[] args) {
		String  source = "serial@/dev/ttyUSB0:tmote";
		String  file = "dati";

		if(args.length == 1) {
			if (!args[0].equals("-h")) {
				usage();
				System.exit(1);
			}
		}
		if (args.length == 2) {
			if (!args[0].equals("-comm")) {
				usage();
				System.exit(1);
			}
			source = args[1];
		}
		else if (args.length == 4) {
			if (!args[0].equals("-comm")) {
				usage();
				System.exit(1);
			}
			source = args[1];
			file = args[3];
		}
		else if (args.length != 0) {
			usage();
			System.exit(1);
		}

		PhoenixSource phoenix;

		if (source == null) {
			phoenix = BuildSource.makePhoenix(PrintStreamMessenger.err);
		}
		else {
			phoenix = BuildSource.makePhoenix(source, PrintStreamMessenger.err);
		}

		MoteIF mif = new MoteIF(phoenix);
		new OutputSaver(mif,file,source);
	}
}
